name: CICD pipeline for PR and Cron_jobs
on:
 schedule:
  - cron: "*/1 * * * *"
 push:
  branches: [main]
 pull_request:
  branches: [main]
jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout repository
     uses: actions/checkout@v4
   - name: Running to check PR request
     run: echo "PR and push events are working successfully......"
